file-db:
  build: ./db_server
  ports:
    - "3010:5984"

delete-ms:
  build: ./delete_ms
  environment:
      HOST_PORT: '4030'
      BIND_ADDRESS: '0.0.0.0'
      HOST_DATABASE: '192.168.99.101'
      HOST_DATABASE_PORT: '3010'
      DATABASE_NAME: "blinkbox_files"
  ports:
    - "4030:4030"
  links:
    - file-db
