file-db:
  build: ./db_server
  ports:
    - "3010:5984"

delete-ms:
  build: ./delete_ms
  environment:
      HOST_PORT: 4030
      HOST_URL: '0.0.0.0'
      DB_URL: '192.168.99.101'
      DB_PORT: '3010'
      DB_NAME: "blinkbox_files"
  ports:
    - "4030:4030"
  links:
    - file-db
